Steven Pizarro Portfolio Project
stevenp19/portfolio-website pull request #1
Opened 2019-03-30 03:50 UTC by stevenp19

2019-04-01 23:55 UTC, ckopecky requested changes

2019-04-01 23:55 UTC, ckopecky commented on html5up-story/index.html
> +							<p>This project was a study on html and css.</p>
You might say 

```Technology Used: HTML, CSS```

2019-04-01 23:55 UTC, ckopecky commented on html5up-story/index.html
> +							<p>Here is a project where we were working on the box model in CSS.</p>
```Technology Used: HTML, CSS/Box Model```

2019-04-01 23:55 UTC, ckopecky commented on html5up-story/index.html
> +					<section class="spotlight style1 orient-right content-align-left image-position-center onscroll-image-fade-in">
Let's go ahead and get rid of the Latin that doesn't pertain to you.

2019-04-02 00:00 UTC, stevenp19 commented on html5up-story/index.html
> +							<p>This project was a study on html and css.</p>
ok, that sounds better.

2019-04-02 00:02 UTC, stevenp19 commented
ok ill go in vscode now to fix it!

2019-04-02 00:21 UTC, stevenp19 commented
hopefully, I did this right.

2019-04-02 00:21 UTC, merged